baseURL = "https://mataku.today/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "Club Kids Never Die"
hasCJKLanguage = true
theme = "hugo-notepadium"
paginate = 30

[params]
style = "auto"
dateFormat = "Monday, January 2, 2006"
logo = "images/logo.webp"
ogpImage = "images/ogp.jpg"
mainSections = ["2021", "2020"]

[params.syntax]
use = "hljs"
theme = "atom-one-dark"

[params.nav]
showTags = true

[params.assets]
css = ["css/font.css", "css/container.css", "css/ogp.css"]

[outputs]
home = [ "HTML", "RSS" ]

[outputFormats.RSS]
baseName = "feed"

[services.rss]
limit = 10
