[build]
publish = "public"
command = "npm run build && hugo --gc --minify"
functions = "./build"

[context.production.environment]
HUGO_VERSION = "v0.110.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "false"

[context.split1]
command = "hugo --gc --minify"

[context.split1.environment]
HUGO_VERSION = "v0.110.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "v0.110.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "v0.110.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "false"
