backend:
  name: git-gateway
  branch: develop
media_folder: static/images
public_folder: /public
local_backend: true
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/'
    create: true
    preview_path: '{{year}}/{{month}}/{{day}}/'
    slug: '{{year}}/{{month}}/{{day}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', date_format: "YYYY-MM-DD", time_format: "HH:MM" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
