name: Build

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.head_ref || 'develop' }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1
      - name: Set hugo version
        run: |
          echo 'HUGO_VERSION=v0.125.3' | sed 's/v//g' >> $GITHUB_ENV

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}

      - name: Build
        run: hugo --minify --gc
