name: 'Build'

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'v0.84.0'

      - name: Build
        env:
          OGP_API_ENDPOINT: ${{ secrets.OGP_API_ENDPOINT }}
        run: hugo --minify --gc
