name: 'Build'

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
      - name: Set hugo version
        run: |
          echo 'HUGO_VERSION=v0.86.0' | sed 's/v//g' >> $GITHUB_ENV

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}

      - name: Build
        env:
          OGP_API_ENDPOINT: ${{ secrets.OGP_API_ENDPOINT }}
        run: hugo --minify --gc
