name: Hook

on:
  push:
    paths:
      - 'content/**'
    branches:
      - develop

concurrency:
  group: hook
  cancel-in-progress: true

jobs:
  hook:
    runs-on: ubuntu-24.04
    steps:
      - name: Await CF Pages
        uses: WalshyDev/cf-pages-await@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          project: ${{ secrets.CLOUDFLARE_PROJECT }}
      - uses: azu/rss-to-twitter@v2
        with:
          RSS_URL: 'https://mataku.today/feed.xml'
          TWEET_TEMPLATE: '%url%'
          UPDATE_WITHIN_MINUTES: 60
          TWITTER_APIKEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_APIKEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
